# Programming Assignment_8

### 1. Write a Python Program to Add Two Matrices?

In [6]:
import numpy as np
m1 = np.array([[3, 4], [5, 6]])
m2 = np.array([[8, 9], [0, 6]])
r = np.add(m1, m2)
print(r)

[[11 13]
 [ 5 12]]


### 2. Write a Python Program to Multiply Two Matrices?

In [5]:
import numpy as np

A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]] 

B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]

result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


### 3. Write a Python Program to Transpose a Matrix?

In [7]:
import numpy as np
M1 = np.array([[3, 6, 9], [5, -10, 15], [4,8,12]])
M2 = M1.transpose()
print(M2)

[[  3   5   4]
 [  6 -10   8]
 [  9  15  12]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [3]:
a = input("Enter String").lower()
order = a.split()
order.sort()
for words in order:
    print(words)

Enter StringHello, I am doing my Assignment
am
assignment
doing
hello,
i
my


### 5. Write a Python Program to Remove Punctuation From a String?

In [4]:
punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~''' 
a = input("Enter String")

cleared = ""

for char in a:
    if char not in punctuation:
        cleared += char
print(cleared)

Enter Stringhello! My-Name is Nischay#$%%%Tayal
hello MyName is NischayTayal
